Default: &defaults
  user: postgres
  password: testingisgood
  host: localhost
  port: 5432
  database: CloudTransit
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: CloudTransit_test
  <<: *defaults

Staging:
  database: CloudTransit_staging
  poolsize: 100
  <<: *defaults

Production:
  database: CloudTransit_production
  poolsize: 100
  <<: *defaults
